name: affine

services:
  affine:
    image: ghcr.io/toeverything/affine@latest
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      indexer:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    environment:
      PORT: 3010
      REDIS_SERVER_HOST: redis
      REDIS_SERVER_PORT: 6379
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-affine}
      AFFINE_INDEXER_ENABLED: "true"
      AFFINE_INDEXER_SEARCH_ENDPOINT: http://indexer:9308
      AFFINE_SERVER_HOST: ${AFFINE_SERVER_HOST}
      AFFINE_SERVER_HTTPS: ${AFFINE_SERVER_HTTPS:-true}
      AFFINE_SERVER_EXTERNAL_URL: ${AFFINE_SERVER_EXTERNAL_URL}
      AFFINE_SERVER_SUB_PATH: ${AFFINE_SERVER_SUB_PATH:-}
      MAILER_HOST: ${MAILER_HOST:-smtp.gmail.com}
      MAILER_PORT: ${MAILER_PORT:-587}
      MAILER_USER: ${MAILER_USER:-}
      MAILER_PASSWORD: ${MAILER_PASSWORD:-}
      MAILER_SENDER: ${MAILER_SENDER:-}
      MAILER_IGNORE_TLS: ${MAILER_IGNORE_TLS:-false}
    expose:
      - "3010"
    volumes:
      - type: bind
        source: ./storage/uploads
        target: /root/.affine/storage
        is_directory: true
      - type: bind
        source: ./storage/config
        target: /root/.affine/config
        is_directory: true
    restart: unless-stopped

  affine_migration:
    image: ghcr.io/toeverything/affine@${AFFINE_IMAGE_DIGEST:-sha256:638893c8f62bb7fd0b3028863096f2b057e3c7ca2ac5163574c333698a331f33}
    exclude_from_hc: true
    restart: "no"
    command: ["sh", "-c", "node ./scripts/self-host-predeploy.js"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      indexer:
        condition: service_healthy
    environment:
      REDIS_SERVER_HOST: redis
      REDIS_SERVER_PORT: 6379
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-affine}
      AFFINE_INDEXER_ENABLED: "true"
      AFFINE_INDEXER_SEARCH_ENDPOINT: http://indexer:9308
      AFFINE_SERVER_HOST: ${AFFINE_SERVER_HOST}
      AFFINE_SERVER_HTTPS: ${AFFINE_SERVER_HTTPS:-true}
      AFFINE_SERVER_EXTERNAL_URL: ${AFFINE_SERVER_EXTERNAL_URL}
      AFFINE_SERVER_SUB_PATH: ${AFFINE_SERVER_SUB_PATH:-}
      MAILER_HOST: ${MAILER_HOST:-smtp.gmail.com}
      MAILER_PORT: ${MAILER_PORT:-587}
      MAILER_USER: ${MAILER_USER:-}
      MAILER_PASSWORD: ${MAILER_PASSWORD:-}
      MAILER_SENDER: ${MAILER_SENDER:-}
      MAILER_IGNORE_TLS: ${MAILER_IGNORE_TLS:-false}
    volumes:
      - type: bind
        source: ./storage/uploads
        target: /root/.affine/storage
        is_directory: true
      - type: bind
        source: ./storage/config
        target: /root/.affine/config
        is_directory: true

  redis:
    image: redis:${REDIS_VERSION:-7.4-alpine}
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:${POSTGRES_VERSION:-pg16}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE:-affine}
      POSTGRES_INITDB_ARGS: --data-checksums
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_DATABASE:-affine}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - type: bind
        source: ./storage/postgres
        target: /var/lib/postgresql/data
        is_directory: true
    restart: unless-stopped

  indexer:
    image: manticoresearch/manticore:${MANTICORE_VERSION:-10.1.0}
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://127.0.0.1:9308"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - type: bind
        source: ./storage/manticore
        target: /var/lib/manticore
        is_directory: true
    restart: unless-stopped
